import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import customersRouter from "./customers";
import suppliersRouter from "./suppliers";
import inventoryRouter from "./inventory";
import invoicesRouter from "./invoices";
import employeesRouter from "./employees";
import salaryRouter from "./salary";
import purchaseRouter from "./purchase";
import paymentsRouter from "./payments";
import notificationsRouter from "./notifications";
import settingsRouter from "./settings";
import ewayBillsRouter from "./eway-bills";
import reportsRouter from "./reports";
import seedRouter from "./seed";
import superRouter from "./super";
import messagesRouter from "./messages";
import expensesRouter from "./expenses";
import projectsRouter from "./projects";
import appointmentsRouter from "./appointments";
import crmRouter from "./leads";
import dealsRouter from "./deals";
import leavesRouter from "./leaves";
import usersRouter from "./users";
import companiesRouter from "./companies";
import subscriptionsRouter from "./subscriptions";
import daybookRouter from "./daybook";
import returnsRouter from "./returns";
import cashBankRouter from "./cash-bank";
import backupRouter from "./backup";
import auditLogRouter from "./audit-log";
import categoriesRouter from "./categories";
import unitsRouter from "./units";
import branchesRouter from "./branches";
import rolesRouter from "./roles";
import stockTransactionsRouter from "./stock-transactions";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(customersRouter);
router.use(suppliersRouter);
router.use(inventoryRouter);
router.use(invoicesRouter);
router.use(employeesRouter);
router.use(salaryRouter);
router.use(purchaseRouter);
router.use(paymentsRouter);
router.use(notificationsRouter);
router.use(settingsRouter);
router.use(ewayBillsRouter);
router.use(reportsRouter);
router.use(seedRouter);
router.use(superRouter);
router.use(messagesRouter);
router.use(expensesRouter);
router.use(projectsRouter);
router.use(appointmentsRouter);
router.use(crmRouter);
router.use(dealsRouter);
router.use(leavesRouter);
router.use(usersRouter);
router.use(companiesRouter);
router.use(subscriptionsRouter);
router.use(daybookRouter);
router.use(returnsRouter);
router.use(cashBankRouter);
router.use(backupRouter);
router.use(auditLogRouter);
router.use(categoriesRouter);
router.use(unitsRouter);
router.use(branchesRouter);
router.use(rolesRouter);
router.use(stockTransactionsRouter);

export default router;
